services:
  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-api
    restart: unless-stopped
    network_mode: host
    environment:
      - MODE=native
      - PORT=8082  # Внутренний порт для signal-api
    volumes:
      - ./signal-cli-data:/home/.local/share/signal-cli
    env_file:
      - .env

  bot-450:
    build: .
    container_name: bot-450
    network_mode: host
    depends_on:
      - signal-api
    environment:
      - SERVER_PORT=8080  # Bot-450 на порту 8080
    env_file:
      - .env
