server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
  forward-headers-strategy: native

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: bot-450

  datasource:
    url: jdbc:h2:mem:bot450;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

org:
  atics:
    bot450:
      message: ${SIGNAL_MESSAGE:}
      cron:
        time: ${CRON_TIME:}
    signal:
      api:
        url: ${SIGNAL_API_URL:http://signal-api:8080}
      group:
        name: ${SIGNAL_GROUP_NAME:}
      sender:
        number: ${SIGNAL_SENDER_NUMBER:}
